server:
  port: 8081
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:file:~/testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect